### ISSUE TITLE
Tags methods not needed?

### ISSUE THREAD

**Issue by barryokane** [EndzoneSoftware/Umbraco.Extensions#4]
I suspect that the [Tags](https://github.com/EndzoneSoftware/Umbraco.Extensions/blob/828f0d7ff21d6bf070fe71a895506dc2e511d9db/Endzone.Umbraco.Extensions/PublishedContentExtensions/Tags.cs) is not needed.  I suggest removing it:

* We can use the Umbraco [TagService](https://github.com/umbraco/UmbracoDocs/blob/v7-documentation/Getting-Started/Data/Content-Entry/Tags.md) & [TagQuery](https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web/TagQuery.cs) instead.
* It's a static class and not really an Extension ;)

NB: It might be worth adding an extension for `GetChildrenByTags(oneOrMoreTags)` however.

**Comment by filipesousa20** [comment]
@barryokane imagine you have two pages using the same doc type but have unrelated tags, say What's On page and Offers page. If you use the [TagService](https://github.com/umbraco/UmbracoDocs/blob/v7-documentation/Getting-Started/Data/Content-Entry/Tags.md)'s GetAllTags you will get tags from both pages which is not what's intended. The methods on the extensions's package are there to overcome this and keep tags separate.

Of course we could duplicate doc types and use different tag groups but I figured this wasn't the best option.

**Comment by barryokane** [comment]
Yes, I see what you mean.

In addition TagService probably doesn't use the cache.
